
log:
#  file: ./test.log

local:
  port: 9090

gin:
  mod: debug # release test debug

admin:
  user: admin
  passwd: 12345678

db:
#  type: mysql
  name: test
  port: 33061
  user: root
  passwd: passwd